In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [68]:
df = pd.read_csv(r'C:\Apurva\Data Analytics program\Capstone project\traindata.csv')

In [69]:
df.head()

TripType  VisitNumber Weekday           Upc  ScanCount  \
0         7           20  Friday  7.192192e+09          1   
1         7           20  Friday  6.811311e+10          2   
2        25           28  Friday  8.805520e+11          1   
3        25           28  Friday  8.085947e+10          1   
4        25           28  Friday  4.900004e+09          1   

  DepartmentDescription  FinelineNumber  
0          FROZEN FOODS          9117.0  
1          SERVICE DELI          4010.0  
2            LADIESWEAR           313.0  
3            LADIESWEAR          4447.0  
4           DSD GROCERY          9538.0

In [70]:
df.isnull().sum()

TripType                 0
VisitNumber              0
Weekday                  0
Upc                      0
ScanCount                0
DepartmentDescription    0
FinelineNumber           0
dtype: int64

In [71]:
df.head()

TripType  VisitNumber Weekday           Upc  ScanCount  \
0         7           20  Friday  7.192192e+09          1   
1         7           20  Friday  6.811311e+10          2   
2        25           28  Friday  8.805520e+11          1   
3        25           28  Friday  8.085947e+10          1   
4        25           28  Friday  4.900004e+09          1   

  DepartmentDescription  FinelineNumber  
0          FROZEN FOODS          9117.0  
1          SERVICE DELI          4010.0  
2            LADIESWEAR           313.0  
3            LADIESWEAR          4447.0  
4           DSD GROCERY          9538.0

In [72]:
df['TripType'].value_counts()

38    28525
25    26493
7     22168
Name: TripType, dtype: int64

In [73]:
mapping_TripType = {7:0,25:1,38:2}
df['TripType'] = df['TripType'].apply(lambda x : mapping_TripType[x])


In [74]:
from sklearn.preprocessing import LabelEncoder

In [75]:
le = LabelEncoder()
df['Weekday'] = le.fit_transform(df['Weekday'])
df['DepartmentDescription'] = le.fit_transform(df['DepartmentDescription'])

In [76]:
X = df.iloc[:,1:]
Y = df['TripType']

In [77]:
# without Upc

X1=X.drop(['ScanCount'],axis=1)
X1.drop(['Upc'],axis=1,inplace=True)

In [78]:
# without FinerLineNumber

X2=X.drop(['ScanCount'],axis=1)
X2.drop(['FinelineNumber'],axis=1,inplace=True)


In [81]:
from sklearn.preprocessing import StandardScaler

In [82]:
ss = StandardScaler()
ft_X1 = ss.fit_transform(X1)
ft_X1

array([[-1.75361189, -1.48856214, -0.57735119,  1.87831278],
       [-1.75361189, -1.48856214,  1.69006226,  0.03392691],
       [-1.75346812, -1.48856214,  0.36740441, -1.30123945],
       ...,
       [ 1.684706  ,  0.07941526,  0.05248588, -1.3781641 ],
       [ 1.684706  ,  0.07941526,  0.68232295, -0.39295073],
       [ 1.684706  ,  0.07941526,  0.68232295,  0.47272245]])

In [140]:
ss = StandardScaler()
ft_X2 = ss.fit_transform(X2)
ft_X2

array([[-1.75361189, -1.48856214, -0.28864026, -0.57735119],
       [-1.75361189, -1.48856214,  0.14021923,  1.69006226],
       [-1.75346812, -1.48856214,  5.85947222,  0.36740441],
       ...,
       [ 1.684706  ,  0.07941526, -0.31533581,  0.05248588],
       [ 1.684706  ,  0.07941526,  0.28642666,  0.68232295],
       [ 1.684706  ,  0.07941526,  0.28545234,  0.68232295]])

In [84]:
# Divide data into test and train
from sklearn.model_selection import train_test_split

In [86]:
x1train, x1test, y1train, y1test = train_test_split(X1,Y,test_size = 0.20, random_state = 40)

In [87]:
x2train, x2test, y2train, y2test = train_test_split(X2,Y,test_size = 0.20, random_state = 40)

In [88]:
x1train.shape, x1test.shape, y1train.shape, y1test.shape

((61748, 4), (15438, 4), (61748,), (15438,))

In [89]:
x2train.shape, x2test.shape, y2train.shape, y2test.shape

((61748, 4), (15438, 4), (61748,), (15438,))

In [90]:
from sklearn.linear_model import LogisticRegression

In [100]:
lr_m1 = LogisticRegression()
lr_m1.fit(x1train,y1train)

LogisticRegression()

In [108]:
pred_lr = lr_m1.predict(x1test)
pred_lr

array([2, 1, 0, ..., 2, 2, 2], dtype=int64)

In [110]:
from sklearn.metrics import accuracy_score, classification_report

In [104]:
accuracy_score(y1test,pred_lr)

0.46936131623267263

In [111]:
print(classification_report(y1test,pred_lr))

              precision    recall  f1-score   support

           0       0.40      0.31      0.35      4408
           1       0.50      0.54      0.52      5317
           2       0.48      0.52      0.50      5713

    accuracy                           0.47     15438
   macro avg       0.46      0.46      0.46     15438
weighted avg       0.46      0.47      0.46     15438



In [116]:
lr_m2 = LogisticRegression()
lr_m2.fit(x2train,y2train)

LogisticRegression()

In [117]:
pred_lr2 = lr_m2.predict(x2test)
pred_lr2

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [118]:
accuracy_score(y2test,pred_lr2)

0.3444098976551367

In [99]:
# select library
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [106]:
#initialize function
dt_m1 = DecisionTreeClassifier()
rf_m1 = RandomForestClassifier()

In [107]:
#Train Model
dt_m1.fit(x1train,y1train)
rf_m1.fit(x1train,y1train)

RandomForestClassifier()

In [112]:
#Generate prediction
pred_dt = dt_m1.predict(x1test)
pred_dt

array([1, 2, 2, ..., 0, 2, 0], dtype=int64)

In [113]:
#Generate prediction
pred_rf = rf_m1.predict(x1test)
pred_rf

array([1, 2, 2, ..., 0, 2, 2], dtype=int64)

In [114]:
accuracy_score(y1test,pred_dt)

0.7170617955693742

In [115]:
accuracy_score(y1test,pred_rf)

0.7453037958284752

In [119]:
#Predict Label for test data.

In [120]:
df_test = pd.read_csv(r'C:\Apurva\Data Analytics program\Capstone project\testdata.csv')

In [124]:
df_test.head()

VisitNumber Weekday           Upc  ScanCount DepartmentDescription  \
0           87  Friday  7.106841e+09          1          FROZEN FOODS   
1          361  Friday  6.727878e+10          1             MENS WEAR   
2          385  Friday  2.840007e+09          1           DSD GROCERY   
3          413  Friday  2.200000e+09          1   IMPULSE MERCHANDISE   
4          462  Friday  7.282133e+10          1    PLUS AND MATERNITY   

   FinelineNumber  
0            4063  
1            1605  
2            4551  
3             135  
4             744

In [125]:
df_test.isnull().sum()

VisitNumber              0
Weekday                  0
Upc                      0
ScanCount                0
DepartmentDescription    0
FinelineNumber           0
dtype: int64

In [128]:
le = LabelEncoder()
df_test['Weekday'] = le.fit_transform(df_test['Weekday'])
df_test['DepartmentDescription'] = le.fit_transform(df_test['DepartmentDescription'])

In [129]:
df_test.head()

VisitNumber  Weekday           Upc  ScanCount  DepartmentDescription  \
0           87        0  7.106841e+09          1                     18   
1          361        0  6.727878e+10          1                     37   
2          385        0  2.840007e+09          1                     14   
3          413        0  2.200000e+09          1                     27   
4          462        0  7.282133e+10          1                     45   

   FinelineNumber  
0            4063  
1            1605  
2            4551  
3             135  
4             744

In [155]:
# without Upc

X_test=df_test.drop(['ScanCount'],axis=1)
X_test.drop(['Upc'],axis=1,inplace=True)


In [156]:
X_test.head()

VisitNumber  Weekday  DepartmentDescription  FinelineNumber
0           87        0                     18            4063
1          361        0                     37            1605
2          385        0                     14            4551
3          413        0                     27             135
4          462        0                     45             744

In [157]:
ss = StandardScaler()
ft_X_test = ss.fit_transform(X_test)
ft_X_test


array([[-1.7471435 , -1.43075639, -0.54702728,  0.04893194],
       [-1.74223949, -1.43075639,  0.74903037, -0.82499866],
       [-1.74180995, -1.43075639, -0.81988152,  0.22243809],
       ...,
       [ 1.67381446,  0.11341048, -0.88809508, -0.917796  ],
       [ 1.6743693 ,  0.11341048,  0.74903037,  0.57478358],
       [ 1.67581902,  0.11341048,  0.61260325, -0.93308446]])

In [184]:
#Generate prediction
pred_rf_test = rf_m1.predict(X_test)
pred_rf_test


array([2, 0, 2, ..., 2, 2, 1], dtype=int64)

In [185]:
pred_rf_test_df['P_TripType'] = pd.DataFrame(pred_rf_test)

In [193]:
pred_rf_test_df = pred_rf_test_df.iloc[:,1:]

In [194]:
df_test1 = pd.concat([pred_rf_test_df, df_test],axis=1)

In [195]:
df_test1

P_TripType  VisitNumber  Weekday           Upc  ScanCount  \
0              2           87        0  7.106841e+09          1   
1              0          361        0  6.727878e+10          1   
2              2          385        0  2.840007e+09          1   
3              2          413        0  2.200000e+09          1   
4              2          462        0  7.282133e+10          1   
...          ...          ...      ...           ...        ...   
2995           2       191158        3  5.010046e+09          5   
2996           2       191164        3  7.874235e+09          1   
2997           2       191225        3  7.047049e+09          1   
2998           2       191256        3  4.393559e+09          1   
2999           1       191337        3  2.259120e+10          1   

      DepartmentDescription  FinelineNumber  
0                        18            4063  
1                        37            1605  
2                        14            4551  
3                        27             135  
4                        45             744  
...                     ...             ...  
2995                     18            4138  
2996                     13            1508  
2997                     13            1344  
2998                     37            5542  
2999                     35            1301  

[3000 rows x 7 columns]

In [197]:
mapping_TripType_rev = {0:7,1:25,2:38}
df_test1['TripType'] = df_test1['P_TripType'].apply(lambda x : mapping_TripType_rev[x])


In [198]:
df_test1

P_TripType  VisitNumber  Weekday           Upc  ScanCount  \
0              2           87        0  7.106841e+09          1   
1              0          361        0  6.727878e+10          1   
2              2          385        0  2.840007e+09          1   
3              2          413        0  2.200000e+09          1   
4              2          462        0  7.282133e+10          1   
...          ...          ...      ...           ...        ...   
2995           2       191158        3  5.010046e+09          5   
2996           2       191164        3  7.874235e+09          1   
2997           2       191225        3  7.047049e+09          1   
2998           2       191256        3  4.393559e+09          1   
2999           1       191337        3  2.259120e+10          1   

      DepartmentDescription  FinelineNumber  TripType  
0                        18            4063        38  
1                        37            1605         7  
2                        14            4551        38  
3                        27             135        38  
4                        45             744        38  
...                     ...             ...       ...  
2995                     18            4138        38  
2996                     13            1508        38  
2997                     13            1344        38  
2998                     37            5542        38  
2999                     35            1301        25  

[3000 rows x 8 columns]

In [200]:
df_test1['TripType'].unique()

array([38,  7, 25], dtype=int64)

In [202]:
csv_data = df_test1.to_csv(r'C:\Apurva\Data Analytics program\Capstone project\final_out.csv', index = False) 